### ISSUE TITLE
Recursos não devem estar no plural

### ISSUE THREAD

**Issue by AVG1525** [whoisFreire/todoApp#1]
https://github.com/whoisFreire/todoApp/blob/beb067d3f75b4dd13f2e772794b8885f9d4d1f84/Controllers/TodoController.cs#L12

Seus recursos não devem estar no plural. Caso queira obter todos os todos é só bater numa no recurso /Todo/ com o verbo HTTP GET

**Comment by AVG1525** [comment]
Na real, troca esse Route aí por isso [Route("api/v1/[controller]")]. Seu recurso ficará da seguinte forma /api/v1/Todo.

Caso queria adicionar ou remover algo fica a vontade.

**Comment by whoisFreire** [comment]
show , irei fazer isso!
